### ISSUE TITLE
Minor typo on Laravel Quick Start

### ISSUE THREAD

**Issue by ckieffer** [DirectoryTree/LdapRecord.com#2]
I believe "config/dap.php" should be "config/ldap.php" on the QuickStart page.

From https://ldaprecord.com/docs/laravel/quickstart/#usage

### Step 4: Use LdapRecord
To begin, you may either use the built-in models that LdapRecord comes with, or you may create your own models that reference the connection you have created in your config/dap.php file.

**Comment by stevebauman** [comment]
Ah great find thanks @ckieffer! Much appreciated.

Will have this fixed shortly 👍
